/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameLogin;

import javax.swing.JOptionPane;
import arogyaapp.dbutil.DBConnection;
import arogyaapp.pojo.UserProfile;

/**
 *
 * @author vishal chandravanshi
 */
public class ManageReceptionist extends javax.swing.JFrame {

    /**
     * Creates new form ManageReceptionist
     */
    public ManageReceptionist() {
        initComponents();
        setName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnViewRecep = new javax.swing.JButton();
        btnUpdateRecep = new javax.swing.JButton();
        btnRemoveRecep = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        txtName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnAddRecep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/doctor.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 170));

        btnViewRecep.setBackground(new java.awt.Color(0, 255, 255));
        btnViewRecep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewRecep.setText("VIEW RECEPTIONIST");
        btnViewRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecepActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 250, 55));

        btnUpdateRecep.setBackground(new java.awt.Color(0, 255, 255));
        btnUpdateRecep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdateRecep.setText("UPDATE RECEPTIONIST");
        btnUpdateRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRecepActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdateRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 212, 250, 56));

        btnRemoveRecep.setBackground(new java.awt.Color(0, 255, 255));
        btnRemoveRecep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRemoveRecep.setText("REMOVE RECEPTIONIST");
        btnRemoveRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveRecepActionPerformed(evt);
            }
        });
        jPanel3.add(btnRemoveRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(758, 212, 260, 57));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hello user-");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, 60));

        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel5.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        txtName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 150, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 680, 80));

        btnBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 270, -1, -1));

        btnAddRecep.setBackground(new java.awt.Color(0, 255, 255));
        btnAddRecep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddRecep.setText("ADD RECEPTIONIST");
        btnAddRecep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecepActionPerformed(evt);
            }
        });
        jPanel3.add(btnAddRecep, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 250, 60));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Receptionist");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 80));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1070, 310));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Arogya Application");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 1130, 420));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecepActionPerformed
        ViewReceptionistScreen mef = new ViewReceptionistScreen ();
        mef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnViewRecepActionPerformed

    private void btnUpdateRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRecepActionPerformed

        UpdateReceptionistScreen mef = new UpdateReceptionistScreen();
        mef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUpdateRecepActionPerformed

    private void btnRemoveRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRecepActionPerformed
        RemoveReceptionist mef = new RemoveReceptionist();
        mef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRemoveRecepActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        AdminOptionFrameJava frame=new  AdminOptionFrameJava();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddRecepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecepActionPerformed
        // TODO add your handling code here:
       AddReceptionistScreen mef = new AddReceptionistScreen();
        mef.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnAddRecepActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
         int ans;
        ans = JOptionPane.showConfirmDialog(null, "Are you sure to Logout", "LOGOUT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ans == JOptionPane.YES_OPTION) {
          
             LoginScrrenn fr=new LoginScrrenn();
            fr.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReceptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReceptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRecep;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRemoveRecep;
    private javax.swing.JButton btnUpdateRecep;
    private javax.swing.JButton btnViewRecep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables

     private void setName() {
        String name = UserProfile.getUserName();
        txtName.setText(name);
        System.out.println("my name is " + name);
    }
}
