/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameLogin;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import arogyaapp.dao.DoctorsDao;
import arogyaapp.dao.EmpDao;
import arogyaapp.dao.UserDao;
import arogyaapp.dbutil.DBConnection;
import arogyaapp.pojo.DoctorPojo;
import arogyaapp.pojo.UserPojo;
import arogyaapp.utility.PasswordEncryption;

/**
 *
 * @author vishal chandravanshi
 */
public class RegisterDoctorFrame extends javax.swing.JFrame {

    private Map<String, String> unResDoctors;
    private String loginId, selEmpName, selEmpId;
    private String pwd1, pwd2;
    private String contactNo, emailId, qualification, specialist;

    public RegisterDoctorFrame() {
        initComponents();
        unResDoctors = new HashMap<String, String>();
        loadDoctorDetail();
        getNewDoctorId();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDocName = new javax.swing.JTextField();
        txtLoginId = new javax.swing.JTextField();
        txtDoctorId = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        jcbEmpId = new javax.swing.JComboBox<>();
        jcbGender = new javax.swing.JComboBox<>();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtQualification = new javax.swing.JTextField();
        txtSpecialist = new javax.swing.JTextField();
        txtGmailId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setText("Arogya Application");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/HomePageBG1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -110, 1190, 410));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Doctor's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Employee Id");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel4.setBackground(new java.awt.Color(51, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Doctor Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel5.setBackground(new java.awt.Color(51, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Login Id");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel6.setBackground(new java.awt.Color(51, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, 20));

        jLabel7.setBackground(new java.awt.Color(51, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ReType Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Gender");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtDocName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDocName.setEnabled(false);
        jPanel2.add(txtDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 240, -1));

        txtLoginId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtLoginId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 240, -1));

        txtDoctorId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtDoctorId.setEnabled(false);
        jPanel2.add(txtDoctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 200, -1));

        txtContactNo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 90, 200, -1));

        jcbEmpId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbEmpId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jcbEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbEmpIdActionPerformed(evt);
            }
        });
        jPanel2.add(jcbEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 240, -1));

        jcbGender.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male ", "Female", " " }));
        jPanel2.add(jcbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 240, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 240, -1));

        txtRePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtRePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRePasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 240, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Doctor ID");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Gmail ID");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 230, 90, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Contact No");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, -1, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Qualification");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Specialist");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        txtQualification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtQualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, 200, -1));

        txtSpecialist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, 200, -1));

        txtGmailId.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(txtGmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 980, 320));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Add Doctor's Frame");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sanjeevaniapp/icons/icons/images (2).jpg"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, 220, 230));

        btnRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, 220, 40));

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 660, -1, -1));

        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 255, 255));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 660, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRePasswordActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        DoctorUsingOptionFrame fr = new DoctorUsingOptionFrame();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if (validInputs() == false) {
            JOptionPane.showMessageDialog(null, "please Input All The Fields ");
            return;
        }
        String passwordValid = matchPassword();

        if (passwordValid != null) {
            JOptionPane.showMessageDialog(null, passwordValid);
            return;
        }
        if (isContactNoValid() == false) {
            JOptionPane.showMessageDialog(null, "Invalid Mobile Number ");
            return;
        }
        try {
            DoctorPojo doc = new DoctorPojo();
            doc.setDoctorId(txtDoctorId.getText());
            //doc.setDoctorName(selEmpName);
            doc.setDoctorName(txtDocName.getText().trim());
            doc.setContactNo(contactNo);
            doc.setQualification(qualification);
            doc.setEmailId(emailId);
            doc.setGender(jcbGender.getSelectedItem().toString());
            doc.setSpecialist(specialist);

            UserPojo user = new UserPojo();
            user.setLoginId(loginId);
            String encPassword = new String(PasswordEncryption.getEncryption(pwd1.toCharArray()));
            user.setPassword(encPassword);
            user.setUserName(selEmpName);
            user.setUserType("DOCTOR");

            boolean result1 = DoctorsDao.addDoctor(doc);
            boolean result2 = UserDao.addUser(user);

            if (result1 == true && result2 == true) {
                JOptionPane.showMessageDialog(null, "Doctor Resitered Successfully ");
                clearAll();
                getNewDoctorId();
                return;
            }
            JOptionPane.showMessageDialog(null, "Registration UnSuccessfully ");
            return;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error in DB " + e);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void jcbEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbEmpIdActionPerformed
        // TODO add your handling code here:
       // if (jcbEmpId.getSelectedIndex() == null) {
          //  return;
       // }
       
    if (jcbEmpId.getSelectedItem() == null) {
        return;
    }
        
        //selEmpId = jcbEmpId.getSelectedItem().toString();
        //selEmpName = unResDoctors.get(selEmpId);
        //txtDocName.setText(selEmpName);
        String selected = jcbEmpId.getSelectedItem().toString().trim();

    if (selected.isEmpty()) {
        txtDocName.setText("");
        selEmpName = null;
        return;
    }

    selEmpId = selected;
    selEmpName = unResDoctors.get(selEmpId);

    if (selEmpName != null) {
        txtDocName.setText(selEmpName);
    } else {
        txtDocName.setText("");
        JOptionPane.showMessageDialog(null, "Doctor name not found for selected Employee ID");
    }

    }//GEN-LAST:event_jcbEmpIdActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
          int ans;
        ans = JOptionPane.showConfirmDialog(null, "Are you sure to Logout", "LOGOUT", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (ans == JOptionPane.YES_OPTION) {
          
             LoginScrrenn fr=new LoginScrrenn();
            fr.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterDoctorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterDoctorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jcbEmpId;
    private javax.swing.JComboBox<String> jcbGender;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtDocName;
    private javax.swing.JTextField txtDoctorId;
    private javax.swing.JTextField txtGmailId;
    private javax.swing.JTextField txtLoginId;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtQualification;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtSpecialist;
    // End of variables declaration//GEN-END:variables

    private void loadDoctorDetail() {
        try {
            System.out.println("present in loadDoctor ");
            unResDoctors = EmpDao.getUnRegisteredDoctors();

            Set<String> empIdSet = unResDoctors.keySet();
            System.out.println(unResDoctors);

            for (String empId : empIdSet) {
                jcbEmpId.addItem(empId);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error in DB RegisterDoctor Frame " + e);
            e.printStackTrace();
        }
    }

    private void getNewDoctorId() {

        try {
            String docId = DoctorsDao.getNewDoctorId();
            txtDoctorId.setText(docId);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error in DB" + e);
            e.printStackTrace();
        }
    }

    private boolean validInputs() {

        this.loginId = this.txtLoginId.getText().trim();
        char p1[] = this.txtPassword.getPassword();
        char p2[] = this.txtRePassword.getPassword();
        this.contactNo = txtContactNo.getText().trim();
        this.qualification = txtQualification.getText().trim();
        this.emailId = txtGmailId.getText().trim();
        this.specialist = txtSpecialist.getText().trim();
        if (loginId.isEmpty() || p1.length == 0 || p2.length == 0 || contactNo.isEmpty() || qualification.isEmpty() || emailId.isEmpty() || specialist.isEmpty()) {
            return false;
        }
        pwd1 = new String(p1);
        pwd2 = new String(p2);
        return true;

    }

    private String matchPassword() {

        pwd1 = pwd1.trim();
        pwd2 = pwd2.trim();
        if (pwd1.length() < 3 || pwd2.length() < 3) {
            return "Password must be at least three character ";
        }
        if (pwd1.equals(pwd2) == false) {
            return "Password do not match ";
        }
        return null;
    }

    private boolean isContactNoValid() {

        char[] mob = contactNo.toCharArray();
        for (char ch : mob) {
            if (Character.isDigit(ch) == false) {
                return false;
            }

        }
        if (contactNo.length() == 10) {
            return true;
        }
        return false;
    }

    private void clearAll() {

        txtLoginId.setText("");
        this.txtContactNo.setText("");
        this.txtSpecialist.setText("");
        this.txtDocName.setText("");
        //this.txtDoctorId.setText("");
        this.txtQualification.setText("");
        this.txtGmailId.setText("");
        this.txtPassword.setText("");
        this.txtRePassword.setText("");
        this.unResDoctors.remove(selEmpId);
        this.jcbEmpId.removeItem(selEmpId);

        if (unResDoctors.size() == 0) {
            JOptionPane.showMessageDialog(null, "All Doctors Registersed");
            DoctorUsingOptionFrame fr = new DoctorUsingOptionFrame();
            fr.setVisible(true);
            this.dispose();
        }

    }

}
